job:
  KIND: DeploymentJob
  staging_alias: "champion"
  production_alias: "production"
  registry_model_name: "rag-chatbot-with-guardrails"
  llm_confs: "/confs/rag_chain_config.yaml"
  llm_model_code_path: "/src/llmops_project/models/chatbot_with_guardrails.py"
  vector_store_path: "http://localhost:6333" 
  qa_dataset_path: "/data/datasets/rag_dataset.csv"
  alias: "champion"

  metric_tresholds:
    flesch_kincaid_grade_level_mean: 5.1 # bigger than
    ari_grade_level_mean: 4.1 # bigger than
